START::DEFP()---<record>
001::REPL(EOL,)---<controlfield tag="001"><:SN::SN:></controlfield>
041a::REPL(EOL,)::MINLW(82)---<datafield tag="041" ind1=" " ind2=" "><subfield code="a"><:DEMOTHE_LANG::DEMOTHE_LANG::IF(Select:,,ORIG):></subfield></datafield>
088::REPL(EOL,)::MINLW(82)---<datafield tag="088" ind1=" " ind2=" "><subfield code="a"><:DEMOTHE_REP*::DEMOTHE_REP:></subfield></datafield>
100::REP(EOL,)::RANGE(1,1)::MINLW(82)---<datafield tag="100" ind1=" " ind2=" "><subfield code="a"><:DEMOTHE_AU*::DEMOTHE_AU:></subfield><subfield code="x"><:AUTHOR_ID*::AUTHOR_ID:></subfield><:AUTHOR_CONTRIBUTION*::AUTHOR_CONTRIBUTION::IF(,,<subfield code="c">):><:AUTHOR_CONTRIBUTION*::AUTHOR_CONTRIBUTION:><:AUTHOR_CONTRIBUTION*::AUTHOR_CONTRIBUTION::IF(,,</subfield>):><subfield code="u"><:AUTHOR_AFFILIATION*::AUTHOR_AFFILIATION:></subfield><subfield code="m"><:AUTHOR_EMAIL*::AUTHOR_EMAIL:></subfield></datafield>
245a::REPL(EOL,)::MINLW(82)---<datafield tag="245" ind1=" " ind2=" "><subfield code="a"><:DEMOTHE_TITLE::DEMOTHE_TITLE:></subfield><:DEMOTHE_SUBTTL::DEMOTHE_SUBTTL::IF(,,<subfield code="b">):><:DEMOTHE_SUBTTL::DEMOTHE_SUBTTL:><:DEMOTHE_SUBTTL::DEMOTHE_SUBTTL::IF(,,</subfield>):></datafield>
300::REPL(EOL,)::MINLW(82)---<datafield tag="300" ind1=" " ind2=" "><subfield code="a"><:DEMOTHE_NUMP::DEMOTHE_NUMP:></subfield></datafield>
520a::REP(EOL,)::MINLW(82)---<datafield tag="520" ind1=" " ind2=" "><subfield code="a"><:DEMOTHE_ABS::DEMOTHE_ABS:></subfield></datafield>
700a::REP(EOL,)::RANGE(2,1999)::MINLW(82)---<datafield tag="700" ind1=" " ind2=" "><subfield code="a"><:DEMOTHE_AU*::DEMOTHE_AU:></subfield><subfield code="x"><:AUTHOR_ID*::AUTHOR_ID:></subfield><:AUTHOR_CONTRIBUTION*::AUTHOR_CONTRIBUTION::IF(,,<subfield code="c">):><:AUTHOR_CONTRIBUTION*::AUTHOR_CONTRIBUTION:><:AUTHOR_CONTRIBUTION*::AUTHOR_CONTRIBUTION::IF(,,</subfield>):><subfield code="u"><:AUTHOR_AFFILIATION*::AUTHOR_AFFILIATION:></subfield><subfield code="m"><:AUTHOR_EMAIL*::AUTHOR_EMAIL:></subfield></datafield>
700a::REP(EOL,)::MINLW(116)---<datafield tag="700" ind1=" " ind2=" "><subfield code="a"><:DEMOTHE_SUPERV*::DEMOTHE_SUPERV:></subfield><subfield code="e">dir.</subfield></datafield>
END::DEFP()---</record>
